// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPbCgkzlXdLNE5lKzl7YOgiXfiG84iio0',
    appId: '1:745984118548:web:69350287d5f3e5ad9bbc01',
    messagingSenderId: '745984118548',
    projectId: 'flutter-ordersheet',
    authDomain: 'flutter-ordersheet.firebaseapp.com',
    storageBucket: 'flutter-ordersheet.appspot.com',
    measurementId: 'G-V9DQPBFLRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCehwylMo1UCGjjuoYhnpk8yI1zzFtsy4E',
    appId: '1:745984118548:android:ba203b79262527359bbc01',
    messagingSenderId: '745984118548',
    projectId: 'flutter-ordersheet',
    storageBucket: 'flutter-ordersheet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG52SaEPINvEw2UauIG6cV3rgi7Vmdxk4',
    appId: '1:745984118548:ios:8d4106f21e5777909bbc01',
    messagingSenderId: '745984118548',
    projectId: 'flutter-ordersheet',
    storageBucket: 'flutter-ordersheet.appspot.com',
    iosClientId: '745984118548-hf0l3h2h5e3vg6pd2e0vkmcgddusvb97.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
